<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    public function run()
    {
        // Xóa dữ liệu hiện tại trong bảng trước khi thêm dữ liệu mới
        DB::table('districts')->truncate();

        // Thêm dữ liệu giả mẫu
        DB::table('districts')->insert([
            ['id' => 1, 'id_province' => 1, 'name' => 'Quận Ba Đình'],
            ['id' => 2, 'id_province' => 1, 'name' => 'Quận Hoàn Kiếm'],
            ['id' => 3, 'id_province' => 1, 'name' => 'Quận Tây Hồ'],
            ['id' => 4, 'id_province' => 1, 'name' => 'Quận Long Biên'],
            ['id' => 5, 'id_province' => 1, 'name' => 'Quận Cầu Giấy'],
            ['id' => 6, 'id_province' => 1, 'name' => 'Quận Đống Đa'],
            ['id' => 7, 'id_province' => 1, 'name' => 'Quận Hai Bà Trưng'],
            ['id' => 8, 'id_province' => 1, 'name' => 'Quận Hoàng Mai'],
            ['id' => 9, 'id_province' => 1, 'name' => 'Quận Thanh Xuân'],
            ['id' => 10, 'id_province' => 1, 'name' => 'Huyện Sóc Sơn'],
            ['id' => 11, 'id_province' => 1, 'name' => 'Huyện Đông Anh'],
            ['id' => 12, 'id_province' => 1, 'name' => 'Huyện Gia Lâm'],
            ['id' => 13, 'id_province' => 1, 'name' => 'Quận Nam Từ Liêm'],
            ['id' => 14, 'id_province' => 1, 'name' => 'Huyện Thanh Trì'],
            ['id' => 15, 'id_province' => 1, 'name' => 'Quận Bắc Từ Liêm'],
            ['id' => 16, 'id_province' => 1, 'name' => 'Huyện Mê Linh'],
            ['id' => 17, 'id_province' => 1, 'name' => 'Quận Hà Đông'],
            ['id' => 18, 'id_province' => 1, 'name' => 'Thị xã Sơn Tây'],
            ['id' => 19, 'id_province' => 1, 'name' => 'Huyện Ba Vì'],
            ['id' => 20, 'id_province' => 1, 'name' => 'Huyện Phúc Thọ'],
            ['id' => 21, 'id_province' => 1, 'name' => 'Huyện Đan Phượng'],
            ['id' => 22, 'id_province' => 1, 'name' => 'Huyện Hoài Đức'],
            ['id' => 23, 'id_province' => 1, 'name' => 'Huyện Quốc Oai'],
            ['id' => 24, 'id_province' => 1, 'name' => 'Huyện Thạch Thất'],
            ['id' => 25, 'id_province' => 1, 'name' => 'Huyện Chương Mỹ'],
            ['id' => 26, 'id_province' => 1, 'name' => 'Huyện Thanh Oai'],
            ['id' => 27, 'id_province' => 1, 'name' => 'Huyện Thường Tín'],
            ['id' => 28, 'id_province' => 1, 'name' => 'Huyện Phú Xuyên'],
            ['id' => 29, 'id_province' => 1, 'name' => 'Huyện Ứng Hòa'],
            ['id' => 30, 'id_province' => 1, 'name' => 'Huyện Mỹ Đức'],
            ['id' => 31, 'id_province' => 2, 'name' => 'Thành phố Hà Giang'],
            ['id' => 32, 'id_province' => 2, 'name' => 'Huyện Đồng Văn'],
            ['id' => 33, 'id_province' => 2, 'name' => 'Huyện Mèo Vạc'],
            ['id' => 34, 'id_province' => 2, 'name' => 'Huyện Yên Minh'],
            ['id' => 35, 'id_province' => 2, 'name' => 'Huyện Quản Bạ'],
            ['id' => 36, 'id_province' => 2, 'name' => 'Huyện Vị Xuyên'],
            ['id' => 37, 'id_province' => 2, 'name' => 'Huyện Bắc Mê'],
            ['id' => 38, 'id_province' => 2, 'name' => 'Huyện Hoàng Su Phì'],
            ['id' => 39, 'id_province' => 2, 'name' => 'Huyện Xín Mần'],
            ['id' => 40, 'id_province' => 2, 'name' => 'Huyện Bắc Quang'],
            ['id' => 41, 'id_province' => 2, 'name' => 'Huyện Quang Bình'],
            ['id' => 42, 'id_province' => 3, 'name' => 'Thành phố Cao Bằng'],
            ['id' => 43, 'id_province' => 3, 'name' => 'Huyện Bảo Lâm'],
            ['id' => 44, 'id_province' => 3, 'name' => 'Huyện Bảo Lạc'],
            ['id' => 45, 'id_province' => 3, 'name' => 'Huyện Hà Quảng'],
            ['id' => 46, 'id_province' => 3, 'name' => 'Huyện Trùng Khánh'],
            ['id' => 47, 'id_province' => 3, 'name' => 'Huyện Hạ Lang'],
            ['id' => 48, 'id_province' => 3, 'name' => 'Huyện Quảng Hòa'],
            ['id' => 49, 'id_province' => 3, 'name' => 'Huyện Hoà An'],
            ['id' => 50, 'id_province' => 3, 'name' => 'Huyện Nguyên Bình'],
            ['id' => 51, 'id_province' => 3, 'name' => 'Huyện Thạch An'],
            ['id' => 52, 'id_province' => 4, 'name' => 'Thành Phố Bắc Kạn'],
            ['id' => 53, 'id_province' => 4, 'name' => 'Huyện Pác Nặm'],
            ['id' => 54, 'id_province' => 4, 'name' => 'Huyện Ba Bể'],
            ['id' => 55, 'id_province' => 4, 'name' => 'Huyện Ngân Sơn'],
            ['id' => 56, 'id_province' => 4, 'name' => 'Huyện Bạch Thông'],
            ['id' => 57, 'id_province' => 4, 'name' => 'Huyện Chợ Đồn'],
            ['id' => 58, 'id_province' => 4, 'name' => 'Huyện Chợ Mới'],
            ['id' => 59, 'id_province' => 4, 'name' => 'Huyện Na Rì'],
            ['id' => 60, 'id_province' => 5, 'name' => 'Thành phố Tuyên Quang'],
            ['id' => 61, 'id_province' => 5, 'name' => 'Huyện Lâm Bình'],
            ['id' => 62, 'id_province' => 5, 'name' => 'Huyện Na Hang'],
            ['id' => 63, 'id_province' => 5, 'name' => 'Huyện Chiêm Hóa'],
            ['id' => 64, 'id_province' => 5, 'name' => 'Huyện Hàm Yên'],
            ['id' => 65, 'id_province' => 5, 'name' => 'Huyện Yên Sơn'],
            ['id' => 66, 'id_province' => 5, 'name' => 'Huyện Sơn Dương'],
            ['id' => 67, 'id_province' => 6, 'name' => 'Thành phố Lào Cai'],
            ['id' => 68, 'id_province' => 6, 'name' => 'Huyện Bát Xát'],
            ['id' => 69, 'id_province' => 6, 'name' => 'Huyện Mường Khương'],
            ['id' => 70, 'id_province' => 6, 'name' => 'Huyện Si Ma Cai'],
            ['id' => 71, 'id_province' => 6, 'name' => 'Huyện Bắc Hà'],
            ['id' => 72, 'id_province' => 6, 'name' => 'Huyện Bảo Thắng'],
            ['id' => 73, 'id_province' => 6, 'name' => 'Huyện Bảo Yên'],
            ['id' => 74, 'id_province' => 6, 'name' => 'Thị xã Sa Pa'],
            ['id' => 75, 'id_province' => 6, 'name' => 'Huyện Văn Bàn'],
            ['id' => 76, 'id_province' => 7, 'name' => 'Thành phố Điện Biên Phủ'],
            ['id' => 77, 'id_province' => 7, 'name' => 'Thị Xã Mường Lay'],
            ['id' => 78, 'id_province' => 7, 'name' => 'Huyện Mường Nhé'],
            ['id' => 79, 'id_province' => 7, 'name' => 'Huyện Mường Chà'],
            ['id' => 80, 'id_province' => 7, 'name' => 'Huyện Tủa Chùa'],
            ['id' => 81, 'id_province' => 7, 'name' => 'Huyện Tuần Giáo'],
            ['id' => 82, 'id_province' => 7, 'name' => 'Huyện Điện Biên'],
            ['id' => 83, 'id_province' => 7, 'name' => 'Huyện Điện Biên Đông'],
            ['id' => 84, 'id_province' => 7, 'name' => 'Huyện Mường Ảng'],
            ['id' => 85, 'id_province' => 7, 'name' => 'Huyện Nậm Pồ'],
            ['id' => 86, 'id_province' => 8, 'name' => 'Thành phố Lai Châu'],
            ['id' => 87, 'id_province' => 8, 'name' => 'Huyện Tam Đường'],
            ['id' => 88, 'id_province' => 8, 'name' => 'Huyện Mường Tè'],
            ['id' => 89, 'id_province' => 8, 'name' => 'Huyện Sìn Hồ'],
            ['id' => 90, 'id_province' => 8, 'name' => 'Huyện Phong Thổ'],
            ['id' => 91, 'id_province' => 8, 'name' => 'Huyện Than Uyên'],
            ['id' => 92, 'id_province' => 8, 'name' => 'Huyện Tân Uyên'],
            ['id' => 93, 'id_province' => 8, 'name' => 'Huyện Nậm Nhùn'],
            ['id' => 94, 'id_province' => 9, 'name' => 'Thành phố Sơn La'],
            ['id' => 95, 'id_province' => 9, 'name' => 'Huyện Quỳnh Nhai'],
            ['id' => 96, 'id_province' => 9, 'name' => 'Huyện Thuận Châu'],
            ['id' => 97, 'id_province' => 9, 'name' => 'Huyện Mường La'],
            ['id' => 98, 'id_province' => 9, 'name' => 'Huyện Bắc Yên'],
            ['id' => 99, 'id_province' => 9, 'name' => 'Huyện Phù Yên'],
            ['id' => 100, 'id_province' => 9, 'name' => 'Huyện Mộc Châu'],
            ['id' => 101, 'id_province' => 9, 'name' => 'Huyện Yên Châu'],
            ['id' => 102, 'id_province' => 9, 'name' => 'Huyện Mai Sơn'],
            ['id' => 103, 'id_province' => 9, 'name' => 'Huyện Sông Mã'],
            ['id' => 104, 'id_province' => 9, 'name' => 'Huyện Sốp Cộp'],
            ['id' => 105, 'id_province' => 9, 'name' => 'Huyện Vân Hồ'],
            ['id' => 106, 'id_province' => 10, 'name' => 'Thành phố Yên Bái'],
            ['id' => 107, 'id_province' => 10, 'name' => 'Thị xã Nghĩa Lộ'],
            ['id' => 108, 'id_province' => 10, 'name' => 'Huyện Lục Yên'],
            ['id' => 109, 'id_province' => 10, 'name' => 'Huyện Văn Yên'],
            ['id' => 110, 'id_province' => 10, 'name' => 'Huyện Mù Căng Chải'],
            ['id' => 111, 'id_province' => 10, 'name' => 'Huyện Trấn Yên'],
            ['id' => 112, 'id_province' => 10, 'name' => 'Huyện Trạm Tấu'],
            ['id' => 113, 'id_province' => 10, 'name' => 'Huyện Văn Chấn'],
            ['id' => 114, 'id_province' => 10, 'name' => 'Huyện Yên Bình'],
            ['id' => 115, 'id_province' => 11, 'name' => 'Thành phố Hòa Bình'],
            ['id' => 116, 'id_province' => 11, 'name' => 'Huyện Đà Bắc'],
            ['id' => 117, 'id_province' => 11, 'name' => 'Huyện Lương Sơn'],
            ['id' => 118, 'id_province' => 11, 'name' => 'Huyện Kim Bôi'],
            ['id' => 119, 'id_province' => 11, 'name' => 'Huyện Cao Phong'],
            ['id' => 120, 'id_province' => 11, 'name' => 'Huyện Tân Lạc'],
            ['id' => 121, 'id_province' => 11, 'name' => 'Huyện Mai Châu'],
            ['id' => 122, 'id_province' => 11, 'name' => 'Huyện Lạc Sơn'],
            ['id' => 123, 'id_province' => 11, 'name' => 'Huyện Yên Thủy'],
            ['id' => 124, 'id_province' => 11, 'name' => 'Huyện Lạc Thủy'],
            ['id' => 125, 'id_province' => 12, 'name' => 'Thành phố Thái Nguyên'],
            ['id' => 126, 'id_province' => 12, 'name' => 'Thành phố Sông Công'],
            ['id' => 127, 'id_province' => 12, 'name' => 'Huyện Định Hóa'],
            ['id' => 128, 'id_province' => 12, 'name' => 'Huyện Phú Lương'],
            ['id' => 129, 'id_province' => 12, 'name' => 'Huyện Đồng Hỷ'],
            ['id' => 130, 'id_province' => 12, 'name' => 'Huyện Võ Nhai'],
            ['id' => 131, 'id_province' => 12, 'name' => 'Huyện Đại Từ'],
            ['id' => 132, 'id_province' => 12, 'name' => 'Thị xã Phổ Yên'],
            ['id' => 133, 'id_province' => 12, 'name' => 'Huyện Phú Bình'],
            ['id' => 134, 'id_province' => 13, 'name' => 'Thành phố Lạng Sơn'],
            ['id' => 135, 'id_province' => 13, 'name' => 'Huyện Tràng Định'],
            ['id' => 136, 'id_province' => 13, 'name' => 'Huyện Bình Gia'],
            ['id' => 137, 'id_province' => 13, 'name' => 'Huyện Văn Lãng'],
            ['id' => 138, 'id_province' => 13, 'name' => 'Huyện Cao Lộc'],
            ['id' => 139, 'id_province' => 13, 'name' => 'Huyện Văn Quan'],
            ['id' => 140, 'id_province' => 13, 'name' => 'Huyện Bắc Sơn'],
            ['id' => 141, 'id_province' => 13, 'name' => 'Huyện Hữu Lũng'],
            ['id' => 142, 'id_province' => 13, 'name' => 'Huyện Chi Lăng'],
            ['id' => 143, 'id_province' => 13, 'name' => 'Huyện Lộc Bình'],
            ['id' => 144, 'id_province' => 13, 'name' => 'Huyện Đình Lập'],
            ['id' => 145, 'id_province' => 14, 'name' => 'Thành phố Hạ Long'],
            ['id' => 146, 'id_province' => 14, 'name' => 'Thành phố Móng Cái'],
            ['id' => 147, 'id_province' => 14, 'name' => 'Thành phố Cẩm Phả'],
            ['id' => 148, 'id_province' => 14, 'name' => 'Thành phố Uông Bí'],
            ['id' => 149, 'id_province' => 14, 'name' => 'Huyện Bình Liêu'],
            ['id' => 150, 'id_province' => 14, 'name' => 'Huyện Tiên Yên'],
            ['id' => 151, 'id_province' => 14, 'name' => 'Huyện Đầm Hà'],
            ['id' => 152, 'id_province' => 14, 'name' => 'Huyện Hải Hà'],
            ['id' => 153, 'id_province' => 14, 'name' => 'Huyện Ba Chẽ'],
            ['id' => 154, 'id_province' => 14, 'name' => 'Huyện Vân Đồn'],
            ['id' => 155, 'id_province' => 14, 'name' => 'Thị xã Đông Triều'],
            ['id' => 156, 'id_province' => 14, 'name' => 'Thị xã Quảng Yên'],
            ['id' => 157, 'id_province' => 14, 'name' => 'Huyện Cô Tô'],
            ['id' => 158, 'id_province' => 15, 'name' => 'Thành phố Bắc Giang'],
            ['id' => 159, 'id_province' => 15, 'name' => 'Huyện Yên Thế'],
            ['id' => 160, 'id_province' => 15, 'name' => 'Huyện Tân Yên'],
            ['id' => 161, 'id_province' => 15, 'name' => 'Huyện Lạng Giang'],
            ['id' => 162, 'id_province' => 15, 'name' => 'Huyện Lục Nam'],
            ['id' => 163, 'id_province' => 15, 'name' => 'Huyện Lục Ngạn'],
            ['id' => 164, 'id_province' => 15, 'name' => 'Huyện Sơn Động'],
            ['id' => 165, 'id_province' => 15, 'name' => 'Huyện Yên Dũng'],
            ['id' => 166, 'id_province' => 15, 'name' => 'Huyện Việt Yên'],
            ['id' => 167, 'id_province' => 15, 'name' => 'Huyện Hiệp Hòa'],
            ['id' => 168, 'id_province' => 16, 'name' => 'Thành phố Việt Trì'],
            ['id' => 169, 'id_province' => 16, 'name' => 'Thị xã Phú Thọ'],
            ['id' => 170, 'id_province' => 16, 'name' => 'Huyện Đoan Hùng'],
            ['id' => 171, 'id_province' => 16, 'name' => 'Huyện Hạ Hoà'],
            ['id' => 172, 'id_province' => 16, 'name' => 'Huyện Thanh Ba'],
            ['id' => 173, 'id_province' => 16, 'name' => 'Huyện Phù Ninh'],
            ['id' => 174, 'id_province' => 16, 'name' => 'Huyện Yên Lập'],
            ['id' => 175, 'id_province' => 16, 'name' => 'Huyện Cẩm Khê'],
            ['id' => 176, 'id_province' => 16, 'name' => 'Huyện Tam Nông'],
            ['id' => 177, 'id_province' => 16, 'name' => 'Huyện Lâm Thao'],
            ['id' => 178, 'id_province' => 16, 'name' => 'Huyện Thanh Sơn'],
            ['id' => 179, 'id_province' => 16, 'name' => 'Huyện Thanh Thuỷ'],
            ['id' => 180, 'id_province' => 16, 'name' => 'Huyện Tân Sơn'],
            ['id' => 181, 'id_province' => 17, 'name' => 'Thành phố Vĩnh Yên'],
            ['id' => 182, 'id_province' => 17, 'name' => 'Thành phố Phúc Yên'],
            ['id' => 183, 'id_province' => 17, 'name' => 'Huyện Lập Thạch'],
            ['id' => 184, 'id_province' => 17, 'name' => 'Huyện Tam Dương'],
            ['id' => 185, 'id_province' => 17, 'name' => 'Huyện Tam Đảo'],
            ['id' => 186, 'id_province' => 17, 'name' => 'Huyện Bình Xuyên'],
            ['id' => 187, 'id_province' => 17, 'name' => 'Huyện Yên Lạc'],
            ['id' => 188, 'id_province' => 17, 'name' => 'Huyện Vĩnh Tường'],
            ['id' => 189, 'id_province' => 17, 'name' => 'Huyện Sông Lô'],
            ['id' => 190, 'id_province' => 18, 'name' => 'Thành phố Bắc Ninh'],
            ['id' => 191, 'id_province' => 18, 'name' => 'Huyện Yên Phong'],
            ['id' => 192, 'id_province' => 18, 'name' => 'Huyện Quế Võ'],
            ['id' => 193, 'id_province' => 18, 'name' => 'Huyện Tiên Du'],
            ['id' => 194, 'id_province' => 18, 'name' => 'Thành phố Từ Sơn'],
            ['id' => 195, 'id_province' => 18, 'name' => 'Huyện Thuận Thành'],
            ['id' => 196, 'id_province' => 18, 'name' => 'Huyện Gia Bình'],
            ['id' => 197, 'id_province' => 18, 'name' => 'Huyện Lương Tài'],
            ['id' => 198, 'id_province' => 19, 'name' => 'Thành phố Hải Dương'],
            ['id' => 199, 'id_province' => 19, 'name' => 'Thành phố Chí Linh'],
            ['id' => 200, 'id_province' => 19, 'name' => 'Huyện Nam Sách'],
            ['id' => 201, 'id_province' => 19, 'name' => 'Thị xã Kinh Môn'],
            ['id' => 202, 'id_province' => 19, 'name' => 'Huyện Kim Thành'],
            ['id' => 203, 'id_province' => 19, 'name' => 'Huyện Thanh Hà'],
            ['id' => 204, 'id_province' => 19, 'name' => 'Huyện Cẩm Giàng'],
            ['id' => 205, 'id_province' => 19, 'name' => 'Huyện Bình Giang'],
            ['id' => 206, 'id_province' => 19, 'name' => 'Huyện Gia Lộc'],
            ['id' => 207, 'id_province' => 19, 'name' => 'Huyện Tứ Kỳ'],
            ['id' => 208, 'id_province' => 19, 'name' => 'Huyện Ninh Giang'],
            ['id' => 209, 'id_province' => 19, 'name' => 'Huyện Thanh Miện'],
            ['id' => 210, 'id_province' => 20, 'name' => 'Quận Hồng Bàng'],
            ['id' => 211, 'id_province' => 20, 'name' => 'Quận Ngô Quyền'],
            ['id' => 212, 'id_province' => 20, 'name' => 'Quận Lê Chân'],
            ['id' => 213, 'id_province' => 20, 'name' => 'Quận Hải An'],
            ['id' => 214, 'id_province' => 20, 'name' => 'Quận Kiến An'],
            ['id' => 215, 'id_province' => 20, 'name' => 'Quận Đồ Sơn'],
            ['id' => 216, 'id_province' => 20, 'name' => 'Quận Dương Kinh'],
            ['id' => 217, 'id_province' => 20, 'name' => 'Huyện Thuỷ Nguyên'],
            ['id' => 218, 'id_province' => 20, 'name' => 'Huyện An Dương'],
            ['id' => 219, 'id_province' => 20, 'name' => 'Huyện An Lão'],
            ['id' => 220, 'id_province' => 20, 'name' => 'Huyện Kiến Thuỵ'],
            ['id' => 221, 'id_province' => 20, 'name' => 'Huyện Tiên Lãng'],
            ['id' => 222, 'id_province' => 20, 'name' => 'Huyện Vĩnh Bảo'],
            ['id' => 223, 'id_province' => 20, 'name' => 'Huyện Cát Hải'],
            ['id' => 224, 'id_province' => 20, 'name' => 'Huyện Bạch Long Vĩ'],
            ['id' => 225, 'id_province' => 21, 'name' => 'Thành phố Hưng Yên'],
            ['id' => 226, 'id_province' => 21, 'name' => 'Huyện Văn Lâm'],
            ['id' => 227, 'id_province' => 21, 'name' => 'Huyện Văn Giang'],
            ['id' => 228, 'id_province' => 21, 'name' => 'Huyện Yên Mỹ'],
            ['id' => 229, 'id_province' => 21, 'name' => 'Thị xã Mỹ Hào'],
            ['id' => 230, 'id_province' => 21, 'name' => 'Huyện Ân Thi'],
            ['id' => 231, 'id_province' => 21, 'name' => 'Huyện Khoái Châu'],
            ['id' => 232, 'id_province' => 21, 'name' => 'Huyện Kim Động'],
            ['id' => 233, 'id_province' => 21, 'name' => 'Huyện Tiên Lữ'],
            ['id' => 234, 'id_province' => 21, 'name' => 'Huyện Phù Cừ'],
            ['id' => 235, 'id_province' => 22, 'name' => 'Thành phố Thái Bình'],
            ['id' => 236, 'id_province' => 22, 'name' => 'Huyện Quỳnh Phụ'],
            ['id' => 237, 'id_province' => 22, 'name' => 'Huyện Hưng Hà'],
            ['id' => 238, 'id_province' => 22, 'name' => 'Huyện Đông Hưng'],
            ['id' => 239, 'id_province' => 22, 'name' => 'Huyện Thái Thụy'],
            ['id' => 240, 'id_province' => 22, 'name' => 'Huyện Tiền Hải'],
            ['id' => 241, 'id_province' => 22, 'name' => 'Huyện Kiến Xương'],
            ['id' => 242, 'id_province' => 22, 'name' => 'Huyện Vũ Thư'],
            ['id' => 243, 'id_province' => 23, 'name' => 'Thành phố Phủ Lý'],
            ['id' => 244, 'id_province' => 23, 'name' => 'Thị xã Duy Tiên'],
            ['id' => 245, 'id_province' => 23, 'name' => 'Huyện Kim Bảng'],
            ['id' => 246, 'id_province' => 23, 'name' => 'Huyện Thanh Liêm'],
            ['id' => 247, 'id_province' => 23, 'name' => 'Huyện Bình Lục'],
            ['id' => 248, 'id_province' => 23, 'name' => 'Huyện Lý Nhân'],
            ['id' => 249, 'id_province' => 24, 'name' => 'Thành phố Nam Định'],
            ['id' => 250, 'id_province' => 24, 'name' => 'Huyện Mỹ Lộc'],
            ['id' => 251, 'id_province' => 24, 'name' => 'Huyện Vụ Bản'],
            ['id' => 252, 'id_province' => 24, 'name' => 'Huyện Ý Yên'],
            ['id' => 253, 'id_province' => 24, 'name' => 'Huyện Nghĩa Hưng'],
            ['id' => 254, 'id_province' => 24, 'name' => 'Huyện Nam Trực'],
            ['id' => 255, 'id_province' => 24, 'name' => 'Huyện Trực Ninh'],
            ['id' => 256, 'id_province' => 24, 'name' => 'Huyện Xuân Trường'],
            ['id' => 257, 'id_province' => 24, 'name' => 'Huyện Giao Thủy'],
            ['id' => 258, 'id_province' => 24, 'name' => 'Huyện Hải Hậu'],
            ['id' => 259, 'id_province' => 25, 'name' => 'Thành phố Ninh Bình'],
            ['id' => 260, 'id_province' => 25, 'name' => 'Thành phố Tam Điệp'],
            ['id' => 261, 'id_province' => 25, 'name' => 'Huyện Nho Quan'],
            ['id' => 262, 'id_province' => 25, 'name' => 'Huyện Gia Viễn'],
            ['id' => 263, 'id_province' => 25, 'name' => 'Huyện Hoa Lư'],
            ['id' => 264, 'id_province' => 25, 'name' => 'Huyện Yên Khánh'],
            ['id' => 265, 'id_province' => 25, 'name' => 'Huyện Kim Sơn'],
            ['id' => 266, 'id_province' => 25, 'name' => 'Huyện Yên Mô'],
            ['id' => 267, 'id_province' => 26, 'name' => 'Thành phố Thanh Hóa'],
            ['id' => 268, 'id_province' => 26, 'name' => 'Thị xã Bỉm Sơn'],
            ['id' => 269, 'id_province' => 26, 'name' => 'Thành phố Sầm Sơn'],
            ['id' => 270, 'id_province' => 26, 'name' => 'Huyện Mường Lát'],
            ['id' => 271, 'id_province' => 26, 'name' => 'Huyện Quan Hóa'],
            ['id' => 272, 'id_province' => 26, 'name' => 'Huyện Bá Thước'],
            ['id' => 273, 'id_province' => 26, 'name' => 'Huyện Quan Sơn'],
            ['id' => 274, 'id_province' => 26, 'name' => 'Huyện Lang Chánh'],
            ['id' => 275, 'id_province' => 26, 'name' => 'Huyện Ngọc Lặc'],
            ['id' => 276, 'id_province' => 26, 'name' => 'Huyện Cẩm Thủy'],
            ['id' => 277, 'id_province' => 26, 'name' => 'Huyện Thạch Thành'],
            ['id' => 278, 'id_province' => 26, 'name' => 'Huyện Hà Trung'],
            ['id' => 279, 'id_province' => 26, 'name' => 'Huyện Vĩnh Lộc'],
            ['id' => 280, 'id_province' => 26, 'name' => 'Huyện Yên Định'],
            ['id' => 281, 'id_province' => 26, 'name' => 'Huyện Thọ Xuân'],
            ['id' => 282, 'id_province' => 26, 'name' => 'Huyện Thường Xuân'],
            ['id' => 283, 'id_province' => 26, 'name' => 'Huyện Triệu Sơn'],
            ['id' => 284, 'id_province' => 26, 'name' => 'Huyện Thiệu Hóa'],
            ['id' => 285, 'id_province' => 26, 'name' => 'Huyện Hoằng Hóa'],
            ['id' => 286, 'id_province' => 26, 'name' => 'Huyện Hậu Lộc'],
            ['id' => 287, 'id_province' => 26, 'name' => 'Huyện Nga Sơn'],
            ['id' => 288, 'id_province' => 26, 'name' => 'Huyện Như Xuân'],
            ['id' => 289, 'id_province' => 26, 'name' => 'Huyện Như Thanh'],
            ['id' => 290, 'id_province' => 26, 'name' => 'Huyện Nông Cống'],
            ['id' => 291, 'id_province' => 26, 'name' => 'Huyện Đông Sơn'],
            ['id' => 292, 'id_province' => 26, 'name' => 'Huyện Quảng Xương'],
            ['id' => 293, 'id_province' => 26, 'name' => 'Thị xã Nghi Sơn'],
            ['id' => 294, 'id_province' => 27, 'name' => 'Thành phố Vinh'],
            ['id' => 295, 'id_province' => 27, 'name' => 'Thị xã Cửa Lò'],
            ['id' => 296, 'id_province' => 27, 'name' => 'Thị xã Thái Hoà'],
            ['id' => 297, 'id_province' => 27, 'name' => 'Huyện Quế Phong'],
            ['id' => 298, 'id_province' => 27, 'name' => 'Huyện Quỳ Châu'],
            ['id' => 299, 'id_province' => 27, 'name' => 'Huyện Kỳ Sơn'],
            ['id' => 300, 'id_province' => 27, 'name' => 'Huyện Tương Dương'],
            ['id' => 301, 'id_province' => 27, 'name' => 'Huyện Nghĩa Đàn'],
            ['id' => 302, 'id_province' => 27, 'name' => 'Huyện Quỳ Hợp'],
            ['id' => 303, 'id_province' => 27, 'name' => 'Huyện Quỳnh Lưu'],
            ['id' => 304, 'id_province' => 27, 'name' => 'Huyện Con Cuông'],
            ['id' => 305, 'id_province' => 27, 'name' => 'Huyện Tân Kỳ'],
            ['id' => 306, 'id_province' => 27, 'name' => 'Huyện Anh Sơn'],
            ['id' => 307, 'id_province' => 27, 'name' => 'Huyện Diễn Châu'],
            ['id' => 308, 'id_province' => 27, 'name' => 'Huyện Yên Thành'],
            ['id' => 309, 'id_province' => 27, 'name' => 'Huyện Đô Lương'],
            ['id' => 310, 'id_province' => 27, 'name' => 'Huyện Thanh Chương'],
            ['id' => 311, 'id_province' => 27, 'name' => 'Huyện Nghi Lộc'],
            ['id' => 312, 'id_province' => 27, 'name' => 'Huyện Nam Đàn'],
            ['id' => 313, 'id_province' => 27, 'name' => 'Huyện Hưng Nguyên'],
            ['id' => 314, 'id_province' => 27, 'name' => 'Thị xã Hoàng Mai'],
            ['id' => 315, 'id_province' => 28, 'name' => 'Thành phố Hà Tĩnh'],
            ['id' => 316, 'id_province' => 28, 'name' => 'Thị xã Hồng Lĩnh'],
            ['id' => 317, 'id_province' => 28, 'name' => 'Huyện Hương Sơn'],
            ['id' => 318, 'id_province' => 28, 'name' => 'Huyện Đức Thọ'],
            ['id' => 319, 'id_province' => 28, 'name' => 'Huyện Vũ Quang'],
            ['id' => 320, 'id_province' => 28, 'name' => 'Huyện Nghi Xuân'],
            ['id' => 321, 'id_province' => 28, 'name' => 'Huyện Can Lộc'],
            ['id' => 322, 'id_province' => 28, 'name' => 'Huyện Hương Khê'],
            ['id' => 323, 'id_province' => 28, 'name' => 'Huyện Thạch Hà'],
            ['id' => 324, 'id_province' => 28, 'name' => 'Huyện Cẩm Xuyên'],
            ['id' => 325, 'id_province' => 28, 'name' => 'Huyện Kỳ Anh'],
            ['id' => 326, 'id_province' => 28, 'name' => 'Huyện Lộc Hà'],
            ['id' => 327, 'id_province' => 28, 'name' => 'Thị xã Kỳ Anh'],
            ['id' => 328, 'id_province' => 29, 'name' => 'Thành Phố Đồng Hới'],
            ['id' => 329, 'id_province' => 29, 'name' => 'Huyện Minh Hóa'],
            ['id' => 330, 'id_province' => 29, 'name' => 'Huyện Tuyên Hóa'],
            ['id' => 331, 'id_province' => 29, 'name' => 'Huyện Quảng Trạch'],
            ['id' => 332, 'id_province' => 29, 'name' => 'Huyện Bố Trạch'],
            ['id' => 333, 'id_province' => 29, 'name' => 'Huyện Quảng Ninh'],
            ['id' => 334, 'id_province' => 29, 'name' => 'Huyện Lệ Thủy'],
            ['id' => 335, 'id_province' => 29, 'name' => 'Thị xã Ba Đồn'],
            ['id' => 336, 'id_province' => 30, 'name' => 'Thành phố Đông Hà'],
            ['id' => 337, 'id_province' => 30, 'name' => 'Thị xã Quảng Trị'],
            ['id' => 338, 'id_province' => 30, 'name' => 'Huyện Vĩnh Linh'],
            ['id' => 339, 'id_province' => 30, 'name' => 'Huyện Hướng Hóa'],
            ['id' => 340, 'id_province' => 30, 'name' => 'Huyện Gio Linh'],
            ['id' => 341, 'id_province' => 30, 'name' => 'Huyện Đa Krông'],
            ['id' => 342, 'id_province' => 30, 'name' => 'Huyện Cam Lộ'],
            ['id' => 343, 'id_province' => 30, 'name' => 'Huyện Triệu Phong'],
            ['id' => 344, 'id_province' => 30, 'name' => 'Huyện Hải Lăng'],
            ['id' => 345, 'id_province' => 30, 'name' => 'Huyện Cồn Cỏ'],
            ['id' => 346, 'id_province' => 31, 'name' => 'Thành phố Huế'],
            ['id' => 347, 'id_province' => 31, 'name' => 'Huyện Phong Điền'],
            ['id' => 348, 'id_province' => 31, 'name' => 'Huyện Quảng Điền'],
            ['id' => 349, 'id_province' => 31, 'name' => 'Huyện Phú Vang'],
            ['id' => 350, 'id_province' => 31, 'name' => 'Thị xã Hương Thủy'],
            ['id' => 351, 'id_province' => 31, 'name' => 'Thị xã Hương Trà'],
            ['id' => 352, 'id_province' => 31, 'name' => 'Huyện A Lưới'],
            ['id' => 353, 'id_province' => 31, 'name' => 'Huyện Phú Lộc'],
            ['id' => 354, 'id_province' => 31, 'name' => 'Huyện Nam Đông'],
            ['id' => 355, 'id_province' => 32, 'name' => 'Quận Liên Chiểu'],
            ['id' => 356, 'id_province' => 32, 'name' => 'Quận Thanh Khê'],
            ['id' => 357, 'id_province' => 32, 'name' => 'Quận Hải Châu'],
            ['id' => 358, 'id_province' => 32, 'name' => 'Quận Sơn Trà'],
            ['id' => 359, 'id_province' => 32, 'name' => 'Quận Ngũ Hành Sơn'],
            ['id' => 360, 'id_province' => 32, 'name' => 'Quận Cẩm Lệ'],
            ['id' => 361, 'id_province' => 32, 'name' => 'Huyện Hòa Vang'],
            ['id' => 362, 'id_province' => 32, 'name' => 'Huyện Hoàng Sa'],
            ['id' => 363, 'id_province' => 33, 'name' => 'Thành phố Tam Kỳ'],
            ['id' => 364, 'id_province' => 33, 'name' => 'Thành phố Hội An'],
            ['id' => 365, 'id_province' => 33, 'name' => 'Huyện Tây Giang'],
            ['id' => 366, 'id_province' => 33, 'name' => 'Huyện Đông Giang'],
            ['id' => 367, 'id_province' => 33, 'name' => 'Huyện Đại Lộc'],
            ['id' => 368, 'id_province' => 33, 'name' => 'Thị xã Điện Bàn'],
            ['id' => 369, 'id_province' => 33, 'name' => 'Huyện Duy Xuyên'],
            ['id' => 370, 'id_province' => 33, 'name' => 'Huyện Quế Sơn'],
            ['id' => 371, 'id_province' => 33, 'name' => 'Huyện Nam Giang'],
            ['id' => 372, 'id_province' => 33, 'name' => 'Huyện Phước Sơn'],
            ['id' => 373, 'id_province' => 33, 'name' => 'Huyện Hiệp Đức'],
            ['id' => 374, 'id_province' => 33, 'name' => 'Huyện Thăng Bình'],
            ['id' => 375, 'id_province' => 33, 'name' => 'Huyện Tiên Phước'],
            ['id' => 376, 'id_province' => 33, 'name' => 'Huyện Bắc Trà My'],
            ['id' => 377, 'id_province' => 33, 'name' => 'Huyện Nam Trà My'],
            ['id' => 378, 'id_province' => 33, 'name' => 'Huyện Núi Thành'],
            ['id' => 379, 'id_province' => 33, 'name' => 'Huyện Phú Ninh'],
            ['id' => 380, 'id_province' => 33, 'name' => 'Huyện Nông Sơn'],
            ['id' => 381, 'id_province' => 34, 'name' => 'Thành phố Quảng Ngãi'],
            ['id' => 382, 'id_province' => 34, 'name' => 'Huyện Bình Sơn'],
            ['id' => 383, 'id_province' => 34, 'name' => 'Huyện Trà Bồng'],
            ['id' => 384, 'id_province' => 34, 'name' => 'Huyện Sơn Tịnh'],
            ['id' => 385, 'id_province' => 34, 'name' => 'Huyện Tư Nghĩa'],
            ['id' => 386, 'id_province' => 34, 'name' => 'Huyện Sơn Hà'],
            ['id' => 387, 'id_province' => 34, 'name' => 'Huyện Sơn Tây'],
            ['id' => 388, 'id_province' => 34, 'name' => 'Huyện Minh Long'],
            ['id' => 389, 'id_province' => 34, 'name' => 'Huyện Nghĩa Hành'],
            ['id' => 390, 'id_province' => 34, 'name' => 'Huyện Mộ Đức'],
            ['id' => 391, 'id_province' => 34, 'name' => 'Thị xã Đức Phổ'],
            ['id' => 392, 'id_province' => 34, 'name' => 'Huyện Ba Tơ'],
            ['id' => 393, 'id_province' => 34, 'name' => 'Huyện Lý Sơn'],
            ['id' => 394, 'id_province' => 35, 'name' => 'Thành phố Quy Nhơn'],
            ['id' => 395, 'id_province' => 35, 'name' => 'Huyện An Lão'],
            ['id' => 396, 'id_province' => 35, 'name' => 'Thị xã Hoài Nhơn'],
            ['id' => 397, 'id_province' => 35, 'name' => 'Huyện Hoài Ân'],
            ['id' => 398, 'id_province' => 35, 'name' => 'Huyện Phù Mỹ'],
            ['id' => 399, 'id_province' => 35, 'name' => 'Huyện Vĩnh Thạnh'],
            ['id' => 400, 'id_province' => 35, 'name' => 'Huyện Tây Sơn'],
            ['id' => 401, 'id_province' => 35, 'name' => 'Huyện Phù Cát'],
            ['id' => 402, 'id_province' => 35, 'name' => 'Thị xã An Nhơn'],
            ['id' => 403, 'id_province' => 35, 'name' => 'Huyện Tuy Phước'],
            ['id' => 404, 'id_province' => 35, 'name' => 'Huyện Vân Canh'],
            ['id' => 405, 'id_province' => 36, 'name' => 'Thành phố Tuy Hoà'],
            ['id' => 406, 'id_province' => 36, 'name' => 'Thị xã Sông Cầu'],
            ['id' => 407, 'id_province' => 36, 'name' => 'Huyện Đồng Xuân'],
            ['id' => 408, 'id_province' => 36, 'name' => 'Huyện Tuy An'],
            ['id' => 409, 'id_province' => 36, 'name' => 'Huyện Sơn Hòa'],
            ['id' => 410, 'id_province' => 36, 'name' => 'Huyện Sông Hinh'],
            ['id' => 411, 'id_province' => 36, 'name' => 'Huyện Tây Hoà'],
            ['id' => 412, 'id_province' => 36, 'name' => 'Huyện Phú Hoà'],
            ['id' => 413, 'id_province' => 36, 'name' => 'Thị xã Đông Hòa'],
            ['id' => 414, 'id_province' => 37, 'name' => 'Thành phố Nha Trang'],
            ['id' => 415, 'id_province' => 37, 'name' => 'Thành phố Cam Ranh'],
            ['id' => 416, 'id_province' => 37, 'name' => 'Huyện Cam Lâm'],
            ['id' => 417, 'id_province' => 37, 'name' => 'Huyện Vạn Ninh'],
            ['id' => 418, 'id_province' => 37, 'name' => 'Thị xã Ninh Hòa'],
            ['id' => 419, 'id_province' => 37, 'name' => 'Huyện Khánh Vĩnh'],
            ['id' => 420, 'id_province' => 37, 'name' => 'Huyện Diên Khánh'],
            ['id' => 421, 'id_province' => 37, 'name' => 'Huyện Khánh Sơn'],
            ['id' => 422, 'id_province' => 37, 'name' => 'Huyện Trường Sa'],
            ['id' => 423, 'id_province' => 38, 'name' => 'Thành phố Phan Rang-Tháp Chàm'],
            ['id' => 424, 'id_province' => 38, 'name' => 'Huyện Bác Ái'],
            ['id' => 425, 'id_province' => 38, 'name' => 'Huyện Ninh Sơn'],
            ['id' => 426, 'id_province' => 38, 'name' => 'Huyện Ninh Hải'],
            ['id' => 427, 'id_province' => 38, 'name' => 'Huyện Ninh Phước'],
            ['id' => 428, 'id_province' => 38, 'name' => 'Huyện Thuận Bắc'],
            ['id' => 429, 'id_province' => 38, 'name' => 'Huyện Thuận Nam'],
            ['id' => 430, 'id_province' => 39, 'name' => 'Thành phố Phan Thiết'],
            ['id' => 431, 'id_province' => 39, 'name' => 'Thị xã La Gi'],
            ['id' => 432, 'id_province' => 39, 'name' => 'Huyện Tuy Phong'],
            ['id' => 433, 'id_province' => 39, 'name' => 'Huyện Bắc Bình'],
            ['id' => 434, 'id_province' => 39, 'name' => 'Huyện Hàm Thuận Bắc'],
            ['id' => 435, 'id_province' => 39, 'name' => 'Huyện Hàm Thuận Nam'],
            ['id' => 436, 'id_province' => 39, 'name' => 'Huyện Tánh Linh'],
            ['id' => 437, 'id_province' => 39, 'name' => 'Huyện Đức Linh'],
            ['id' => 438, 'id_province' => 39, 'name' => 'Huyện Hàm Tân'],
            ['id' => 439, 'id_province' => 39, 'name' => 'Huyện Phú Quí'],
            ['id' => 440, 'id_province' => 40, 'name' => 'Thành phố Kon Tum'],
            ['id' => 441, 'id_province' => 40, 'name' => 'Huyện Đắk Glei'],
            ['id' => 442, 'id_province' => 40, 'name' => 'Huyện Ngọc Hồi'],
            ['id' => 443, 'id_province' => 40, 'name' => 'Huyện Đắk Tô'],
            ['id' => 444, 'id_province' => 40, 'name' => 'Huyện Kon Plông'],
            ['id' => 445, 'id_province' => 40, 'name' => 'Huyện Kon Rẫy'],
            ['id' => 446, 'id_province' => 40, 'name' => 'Huyện Đắk Hà'],
            ['id' => 447, 'id_province' => 40, 'name' => 'Huyện Sa Thầy'],
            ['id' => 448, 'id_province' => 40, 'name' => 'Huyện Tu Mơ Rông'],
            ['id' => 449, 'id_province' => 40, 'name' => 'Huyện Ia H\' Drai'],
            ['id' => 450, 'id_province' => 41, 'name' => 'Thành phố Pleiku'],
            ['id' => 451, 'id_province' => 41, 'name' => 'Thị xã An Khê'],
            ['id' => 452, 'id_province' => 41, 'name' => 'Thị xã Ayun Pa'],
            ['id' => 453, 'id_province' => 41, 'name' => 'Huyện KBang'],
            ['id' => 454, 'id_province' => 41, 'name' => 'Huyện Đăk Đoa'],
            ['id' => 455, 'id_province' => 41, 'name' => 'Huyện Chư Păh'],
            ['id' => 456, 'id_province' => 41, 'name' => 'Huyện Ia Grai'],
            ['id' => 457, 'id_province' => 41, 'name' => 'Huyện Mang Yang'],
            ['id' => 458, 'id_province' => 41, 'name' => 'Huyện Kông Chro'],
            ['id' => 459, 'id_province' => 41, 'name' => 'Huyện Đức Cơ'],
            ['id' => 460, 'id_province' => 41, 'name' => 'Huyện Chư Prông'],
            ['id' => 461, 'id_province' => 41, 'name' => 'Huyện Chư Sê'],
            ['id' => 462, 'id_province' => 41, 'name' => 'Huyện Đăk Pơ'],
            ['id' => 463, 'id_province' => 41, 'name' => 'Huyện Ia Pa'],
            ['id' => 464, 'id_province' => 41, 'name' => 'Huyện Krông Pa'],
            ['id' => 465, 'id_province' => 41, 'name' => 'Huyện Phú Thiện'],
            ['id' => 466, 'id_province' => 41, 'name' => 'Huyện Chư Pưh'],
            ['id' => 467, 'id_province' => 42, 'name' => 'Thành phố Buôn Ma Thuột'],
            ['id' => 468, 'id_province' => 42, 'name' => 'Thị Xã Buôn Hồ'],
            ['id' => 469, 'id_province' => 42, 'name' => 'Huyện Ea H\'leo'],
            ['id' => 470, 'id_province' => 42, 'name' => 'Huyện Ea Súp'],
            ['id' => 471, 'id_province' => 42, 'name' => 'Huyện Buôn Đôn'],
            ['id' => 472, 'id_province' => 42, 'name' => 'Huyện Cư M\'gar'],
            ['id' => 473, 'id_province' => 42, 'name' => 'Huyện Krông Búk'],
            ['id' => 474, 'id_province' => 42, 'name' => 'Huyện Krông Năng'],
            ['id' => 475, 'id_province' => 42, 'name' => 'Huyện Ea Kar'],
            ['id' => 476, 'id_province' => 42, 'name' => 'Huyện M\'Đrắk'],
            ['id' => 477, 'id_province' => 42, 'name' => 'Huyện Krông Bông'],
            ['id' => 478, 'id_province' => 42, 'name' => 'Huyện Krông Pắc'],
            ['id' => 479, 'id_province' => 42, 'name' => 'Huyện Krông A Na'],
            ['id' => 480, 'id_province' => 42, 'name' => 'Huyện Lắk'],
            ['id' => 481, 'id_province' => 42, 'name' => 'Huyện Cư Kuin'],
            ['id' => 482, 'id_province' => 43, 'name' => 'Thành phố Gia Nghĩa'],
            ['id' => 483, 'id_province' => 43, 'name' => 'Huyện Đăk Glong'],
            ['id' => 484, 'id_province' => 43, 'name' => 'Huyện Cư Jút'],
            ['id' => 485, 'id_province' => 43, 'name' => 'Huyện Đắk Mil'],
            ['id' => 486, 'id_province' => 43, 'name' => 'Huyện Krông Nô'],
            ['id' => 487, 'id_province' => 43, 'name' => 'Huyện Đắk Song'],
            ['id' => 488, 'id_province' => 43, 'name' => 'Huyện Đắk R\'Lấp'],
            ['id' => 489, 'id_province' => 43, 'name' => 'Huyện Tuy Đức'],
            ['id' => 490, 'id_province' => 44, 'name' => 'Thành phố Đà Lạt'],
            ['id' => 491, 'id_province' => 44, 'name' => 'Thành phố Bảo Lộc'],
            ['id' => 492, 'id_province' => 44, 'name' => 'Huyện Đam Rông'],
            ['id' => 493, 'id_province' => 44, 'name' => 'Huyện Lạc Dương'],
            ['id' => 494, 'id_province' => 44, 'name' => 'Huyện Lâm Hà'],
            ['id' => 495, 'id_province' => 44, 'name' => 'Huyện Đơn Dương'],
            ['id' => 496, 'id_province' => 44, 'name' => 'Huyện Đức Trọng'],
            ['id' => 497, 'id_province' => 44, 'name' => 'Huyện Di Linh'],
            ['id' => 498, 'id_province' => 44, 'name' => 'Huyện Bảo Lâm'],
            ['id' => 499, 'id_province' => 44, 'name' => 'Huyện Đạ Huoai'],
            ['id' => 500, 'id_province' => 44, 'name' => 'Huyện Đạ Tẻh'],
            ['id' => 501, 'id_province' => 44, 'name' => 'Huyện Cát Tiên'],
            ['id' => 502, 'id_province' => 45, 'name' => 'Thị xã Phước Long'],
            ['id' => 503, 'id_province' => 45, 'name' => 'Thành phố Đồng Xoài'],
            ['id' => 504, 'id_province' => 45, 'name' => 'Thị xã Bình Long'],
            ['id' => 505, 'id_province' => 45, 'name' => 'Huyện Bù Gia Mập'],
            ['id' => 506, 'id_province' => 45, 'name' => 'Huyện Lộc Ninh'],
            ['id' => 507, 'id_province' => 45, 'name' => 'Huyện Bù Đốp'],
            ['id' => 508, 'id_province' => 45, 'name' => 'Huyện Hớn Quản'],
            ['id' => 509, 'id_province' => 45, 'name' => 'Huyện Đồng Phú'],
            ['id' => 510, 'id_province' => 45, 'name' => 'Huyện Bù Đăng'],
            ['id' => 511, 'id_province' => 45, 'name' => 'Huyện Chơn Thành'],
            ['id' => 512, 'id_province' => 45, 'name' => 'Huyện Phú Riềng'],
            ['id' => 513, 'id_province' => 46, 'name' => 'Thành phố Tây Ninh'],
            ['id' => 514, 'id_province' => 46, 'name' => 'Huyện Tân Biên'],
            ['id' => 515, 'id_province' => 46, 'name' => 'Huyện Tân Châu'],
            ['id' => 516, 'id_province' => 46, 'name' => 'Huyện Dương Minh Châu'],
            ['id' => 517, 'id_province' => 46, 'name' => 'Huyện Châu Thành'],
            ['id' => 518, 'id_province' => 46, 'name' => 'Thị xã Hòa Thành'],
            ['id' => 519, 'id_province' => 46, 'name' => 'Huyện Gò Dầu'],
            ['id' => 520, 'id_province' => 46, 'name' => 'Huyện Bến Cầu'],
            ['id' => 521, 'id_province' => 46, 'name' => 'Thị xã Trảng Bàng'],
            ['id' => 522, 'id_province' => 47, 'name' => 'Thành phố Thủ Dầu Một'],
            ['id' => 523, 'id_province' => 47, 'name' => 'Huyện Bàu Bàng'],
            ['id' => 524, 'id_province' => 47, 'name' => 'Huyện Dầu Tiếng'],
            ['id' => 525, 'id_province' => 47, 'name' => 'Thị xã Bến Cát'],
            ['id' => 526, 'id_province' => 47, 'name' => 'Huyện Phú Giáo'],
            ['id' => 527, 'id_province' => 47, 'name' => 'Thị xã Tân Uyên'],
            ['id' => 528, 'id_province' => 47, 'name' => 'Thành phố Dĩ An'],
            ['id' => 529, 'id_province' => 47, 'name' => 'Thành phố Thuận An'],
            ['id' => 530, 'id_province' => 47, 'name' => 'Huyện Bắc Tân Uyên'],
            ['id' => 531, 'id_province' => 48, 'name' => 'Thành phố Biên Hòa'],
            ['id' => 532, 'id_province' => 48, 'name' => 'Thành phố Long Khánh'],
            ['id' => 533, 'id_province' => 48, 'name' => 'Huyện Tân Phú'],
            ['id' => 534, 'id_province' => 48, 'name' => 'Huyện Vĩnh Cửu'],
            ['id' => 535, 'id_province' => 48, 'name' => 'Huyện Định Quán'],
            ['id' => 536, 'id_province' => 48, 'name' => 'Huyện Trảng Bom'],
            ['id' => 537, 'id_province' => 48, 'name' => 'Huyện Thống Nhất'],
            ['id' => 538, 'id_province' => 48, 'name' => 'Huyện Cẩm Mỹ'],
            ['id' => 539, 'id_province' => 48, 'name' => 'Huyện Long Thành'],
            ['id' => 540, 'id_province' => 48, 'name' => 'Huyện Xuân Lộc'],
            ['id' => 541, 'id_province' => 48, 'name' => 'Huyện Nhơn Trạch'],
            ['id' => 542, 'id_province' => 49, 'name' => 'Thành phố Vũng Tàu'],
            ['id' => 543, 'id_province' => 49, 'name' => 'Thành phố Bà Rịa'],
            ['id' => 544, 'id_province' => 49, 'name' => 'Huyện Châu Đức'],
            ['id' => 545, 'id_province' => 49, 'name' => 'Huyện Xuyên Mộc'],
            ['id' => 546, 'id_province' => 49, 'name' => 'Huyện Long Điền'],
            ['id' => 547, 'id_province' => 49, 'name' => 'Huyện Đất Đỏ'],
            ['id' => 548, 'id_province' => 49, 'name' => 'Thị xã Phú Mỹ'],
            ['id' => 549, 'id_province' => 49, 'name' => 'Huyện Côn Đảo'],
            ['id' => 550, 'id_province' => 50, 'name' => 'Quận 1'],
            ['id' => 551, 'id_province' => 50, 'name' => 'Quận 12'],
            ['id' => 552, 'id_province' => 50, 'name' => 'Quận Gò Vấp'],
            ['id' => 553, 'id_province' => 50, 'name' => 'Quận Bình Thạnh'],
            ['id' => 554, 'id_province' => 50, 'name' => 'Quận Tân Bình'],
            ['id' => 555, 'id_province' => 50, 'name' => 'Quận Tân Phú'],
            ['id' => 556, 'id_province' => 50, 'name' => 'Quận Phú Nhuận'],
            ['id' => 557, 'id_province' => 50, 'name' => 'Thành phố Thủ Đức'],
            ['id' => 558, 'id_province' => 50, 'name' => 'Quận 3'],
            ['id' => 559, 'id_province' => 50, 'name' => 'Quận 10'],
            ['id' => 560, 'id_province' => 50, 'name' => 'Quận 11'],
            ['id' => 561, 'id_province' => 50, 'name' => 'Quận 4'],
            ['id' => 562, 'id_province' => 50, 'name' => 'Quận 5'],
            ['id' => 563, 'id_province' => 50, 'name' => 'Quận 6'],
            ['id' => 564, 'id_province' => 50, 'name' => 'Quận 8'],
            ['id' => 565, 'id_province' => 50, 'name' => 'Quận Bình Tân'],
            ['id' => 566, 'id_province' => 50, 'name' => 'Quận 7'],
            ['id' => 567, 'id_province' => 50, 'name' => 'Huyện Củ Chi'],
            ['id' => 568, 'id_province' => 50, 'name' => 'Huyện Hóc Môn'],
            ['id' => 569, 'id_province' => 50, 'name' => 'Huyện Bình Chánh'],
            ['id' => 570, 'id_province' => 50, 'name' => 'Huyện Nhà Bè'],
            ['id' => 571, 'id_province' => 50, 'name' => 'Huyện Cần Giờ'],
            ['id' => 572, 'id_province' => 51, 'name' => 'Thành phố Tân An'],
            ['id' => 573, 'id_province' => 51, 'name' => 'Thị xã Kiến Tường'],
            ['id' => 574, 'id_province' => 51, 'name' => 'Huyện Tân Hưng'],
            ['id' => 575, 'id_province' => 51, 'name' => 'Huyện Vĩnh Hưng'],
            ['id' => 576, 'id_province' => 51, 'name' => 'Huyện Mộc Hóa'],
            ['id' => 577, 'id_province' => 51, 'name' => 'Huyện Tân Thạnh'],
            ['id' => 578, 'id_province' => 51, 'name' => 'Huyện Thạnh Hóa'],
            ['id' => 579, 'id_province' => 51, 'name' => 'Huyện Đức Huệ'],
            ['id' => 580, 'id_province' => 51, 'name' => 'Huyện Đức Hòa'],
            ['id' => 581, 'id_province' => 51, 'name' => 'Huyện Bến Lức'],
            ['id' => 582, 'id_province' => 51, 'name' => 'Huyện Thủ Thừa'],
            ['id' => 583, 'id_province' => 51, 'name' => 'Huyện Tân Trụ'],
            ['id' => 584, 'id_province' => 51, 'name' => 'Huyện Cần Đước'],
            ['id' => 585, 'id_province' => 51, 'name' => 'Huyện Cần Giuộc'],
            ['id' => 586, 'id_province' => 51, 'name' => 'Huyện Châu Thành'],
            ['id' => 587, 'id_province' => 52, 'name' => 'Thành phố Mỹ Tho'],
            ['id' => 588, 'id_province' => 52, 'name' => 'Thị xã Gò Công'],
            ['id' => 589, 'id_province' => 52, 'name' => 'Thị xã Cai Lậy'],
            ['id' => 590, 'id_province' => 52, 'name' => 'Huyện Tân Phước'],
            ['id' => 591, 'id_province' => 52, 'name' => 'Huyện Cái Bè'],
            ['id' => 592, 'id_province' => 52, 'name' => 'Huyện Cai Lậy'],
            ['id' => 593, 'id_province' => 52, 'name' => 'Huyện Châu Thành'],
            ['id' => 594, 'id_province' => 52, 'name' => 'Huyện Chợ Gạo'],
            ['id' => 595, 'id_province' => 52, 'name' => 'Huyện Gò Công Tây'],
            ['id' => 596, 'id_province' => 52, 'name' => 'Huyện Gò Công Đông'],
            ['id' => 597, 'id_province' => 52, 'name' => 'Huyện Tân Phú Đông'],
            ['id' => 598, 'id_province' => 53, 'name' => 'Thành phố Bến Tre'],
            ['id' => 599, 'id_province' => 53, 'name' => 'Huyện Châu Thành'],
            ['id' => 600, 'id_province' => 53, 'name' => 'Huyện Chợ Lách'],
            ['id' => 601, 'id_province' => 53, 'name' => 'Huyện Mỏ Cày Nam'],
            ['id' => 602, 'id_province' => 53, 'name' => 'Huyện Giồng Trôm'],
            ['id' => 603, 'id_province' => 53, 'name' => 'Huyện Bình Đại'],
            ['id' => 604, 'id_province' => 53, 'name' => 'Huyện Ba Tri'],
            ['id' => 605, 'id_province' => 53, 'name' => 'Huyện Thạnh Phú'],
            ['id' => 606, 'id_province' => 53, 'name' => 'Huyện Mỏ Cày Bắc'],
            ['id' => 607, 'id_province' => 54, 'name' => 'Thành phố Trà Vinh'],
            ['id' => 608, 'id_province' => 54, 'name' => 'Huyện Càng Long'],
            ['id' => 609, 'id_province' => 54, 'name' => 'Huyện Cầu Kè'],
            ['id' => 610, 'id_province' => 54, 'name' => 'Huyện Tiểu Cần'],
            ['id' => 611, 'id_province' => 54, 'name' => 'Huyện Châu Thành'],
            ['id' => 612, 'id_province' => 54, 'name' => 'Huyện Cầu Ngang'],
            ['id' => 613, 'id_province' => 54, 'name' => 'Huyện Trà Cú'],
            ['id' => 614, 'id_province' => 54, 'name' => 'Huyện Duyên Hải'],
            ['id' => 615, 'id_province' => 54, 'name' => 'Thị xã Duyên Hải'],
            ['id' => 616, 'id_province' => 55, 'name' => 'Thành phố Vĩnh Long'],
            ['id' => 617, 'id_province' => 55, 'name' => 'Huyện Long Hồ'],
            ['id' => 618, 'id_province' => 55, 'name' => 'Huyện Mang Thít'],
            ['id' => 619, 'id_province' => 55, 'name' => 'Huyện  Vũng Liêm'],
            ['id' => 620, 'id_province' => 55, 'name' => 'Huyện Tam Bình'],
            ['id' => 621, 'id_province' => 55, 'name' => 'Thị xã Bình Minh'],
            ['id' => 622, 'id_province' => 55, 'name' => 'Huyện Trà Ôn'],
            ['id' => 623, 'id_province' => 55, 'name' => 'Huyện Bình Tân'],
            ['id' => 624, 'id_province' => 56, 'name' => 'Thành phố Cao Lãnh'],
            ['id' => 625, 'id_province' => 56, 'name' => 'Thành phố Sa Đéc'],
            ['id' => 626, 'id_province' => 56, 'name' => 'Thành phố Hồng Ngự'],
            ['id' => 627, 'id_province' => 56, 'name' => 'Huyện Tân Hồng'],
            ['id' => 628, 'id_province' => 56, 'name' => 'Huyện Hồng Ngự'],
            ['id' => 629, 'id_province' => 56, 'name' => 'Huyện Tam Nông'],
            ['id' => 630, 'id_province' => 56, 'name' => 'Huyện Tháp Mười'],
            ['id' => 631, 'id_province' => 56, 'name' => 'Huyện Cao Lãnh'],
            ['id' => 632, 'id_province' => 56, 'name' => 'Huyện Thanh Bình'],
            ['id' => 633, 'id_province' => 56, 'name' => 'Huyện Lấp Vò'],
            ['id' => 634, 'id_province' => 56, 'name' => 'Huyện Lai Vung'],
            ['id' => 635, 'id_province' => 56, 'name' => 'Huyện Châu Thành'],
            ['id' => 636, 'id_province' => 57, 'name' => 'Thành phố Long Xuyên'],
            ['id' => 637, 'id_province' => 57, 'name' => 'Thành phố Châu Đốc'],
            ['id' => 638, 'id_province' => 57, 'name' => 'Huyện An Phú'],
            ['id' => 639, 'id_province' => 57, 'name' => 'Thị xã Tân Châu'],
            ['id' => 640, 'id_province' => 57, 'name' => 'Huyện Phú Tân'],
            ['id' => 641, 'id_province' => 57, 'name' => 'Huyện Châu Phú'],
            ['id' => 642, 'id_province' => 57, 'name' => 'Huyện Tịnh Biên'],
            ['id' => 643, 'id_province' => 57, 'name' => 'Huyện Tri Tôn'],
            ['id' => 644, 'id_province' => 57, 'name' => 'Huyện Châu Thành'],
            ['id' => 645, 'id_province' => 57, 'name' => 'Huyện Chợ Mới'],
            ['id' => 646, 'id_province' => 57, 'name' => 'Huyện Thoại Sơn'],
            ['id' => 647, 'id_province' => 58, 'name' => 'Thành phố Rạch Giá'],
            ['id' => 648, 'id_province' => 58, 'name' => 'Thành phố Hà Tiên'],
            ['id' => 649, 'id_province' => 58, 'name' => 'Huyện Kiên Lương'],
            ['id' => 650, 'id_province' => 58, 'name' => 'Huyện Hòn Đất'],
            ['id' => 651, 'id_province' => 58, 'name' => 'Huyện Tân Hiệp'],
            ['id' => 652, 'id_province' => 58, 'name' => 'Huyện Châu Thành'],
            ['id' => 653, 'id_province' => 58, 'name' => 'Huyện Giồng Riềng'],
            ['id' => 654, 'id_province' => 58, 'name' => 'Huyện Gò Quao'],
            ['id' => 655, 'id_province' => 58, 'name' => 'Huyện An Biên'],
            ['id' => 656, 'id_province' => 58, 'name' => 'Huyện An Minh'],
            ['id' => 657, 'id_province' => 58, 'name' => 'Huyện Vĩnh Thuận'],
            ['id' => 658, 'id_province' => 58, 'name' => 'Thành phố Phú Quốc'],
            ['id' => 659, 'id_province' => 58, 'name' => 'Huyện Kiên Hải'],
            ['id' => 660, 'id_province' => 58, 'name' => 'Huyện U Minh Thượng'],
            ['id' => 661, 'id_province' => 58, 'name' => 'Huyện Giang Thành'],
            ['id' => 662, 'id_province' => 59, 'name' => 'Quận Ninh Kiều'],
            ['id' => 663, 'id_province' => 59, 'name' => 'Quận Ô Môn'],
            ['id' => 664, 'id_province' => 59, 'name' => 'Quận Bình Thuỷ'],
            ['id' => 665, 'id_province' => 59, 'name' => 'Quận Cái Răng'],
            ['id' => 666, 'id_province' => 59, 'name' => 'Quận Thốt Nốt'],
            ['id' => 667, 'id_province' => 59, 'name' => 'Huyện Vĩnh Thạnh'],
            ['id' => 668, 'id_province' => 59, 'name' => 'Huyện Cờ Đỏ'],
            ['id' => 669, 'id_province' => 59, 'name' => 'Huyện Phong Điền'],
            ['id' => 670, 'id_province' => 59, 'name' => 'Huyện Thới Lai'],
            ['id' => 671, 'id_province' => 60, 'name' => 'Thành phố Vị Thanh'],
            ['id' => 672, 'id_province' => 60, 'name' => 'Thành phố Ngã Bảy'],
            ['id' => 673, 'id_province' => 60, 'name' => 'Huyện Châu Thành A'],
            ['id' => 674, 'id_province' => 60, 'name' => 'Huyện Châu Thành'],
            ['id' => 675, 'id_province' => 60, 'name' => 'Huyện Phụng Hiệp'],
            ['id' => 676, 'id_province' => 60, 'name' => 'Huyện Vị Thuỷ'],
            ['id' => 677, 'id_province' => 60, 'name' => 'Huyện Long Mỹ'],
            ['id' => 678, 'id_province' => 60, 'name' => 'Thị xã Long Mỹ'],
            ['id' => 679, 'id_province' => 61, 'name' => 'Thành phố Sóc Trăng'],
            ['id' => 680, 'id_province' => 61, 'name' => 'Huyện Châu Thành'],
            ['id' => 681, 'id_province' => 61, 'name' => 'Huyện Kế Sách'],
            ['id' => 682, 'id_province' => 61, 'name' => 'Huyện Mỹ Tú'],
            ['id' => 683, 'id_province' => 61, 'name' => 'Huyện Cù Lao Dung'],
            ['id' => 684, 'id_province' => 61, 'name' => 'Huyện Long Phú'],
            ['id' => 685, 'id_province' => 61, 'name' => 'Huyện Mỹ Xuyên'],
            ['id' => 686, 'id_province' => 61, 'name' => 'Thị xã Ngã Năm'],
            ['id' => 687, 'id_province' => 61, 'name' => 'Huyện Thạnh Trị'],
            ['id' => 688, 'id_province' => 61, 'name' => 'Thị xã Vĩnh Châu'],
            ['id' => 689, 'id_province' => 61, 'name' => 'Huyện Trần Đề'],
            ['id' => 690, 'id_province' => 62, 'name' => 'Thành phố Bạc Liêu'],
            ['id' => 691, 'id_province' => 62, 'name' => 'Huyện Hồng Dân'],
            ['id' => 692, 'id_province' => 62, 'name' => 'Huyện Phước Long'],
            ['id' => 693, 'id_province' => 62, 'name' => 'Huyện Vĩnh Lợi'],
            ['id' => 694, 'id_province' => 62, 'name' => 'Thị xã Giá Rai'],
            ['id' => 695, 'id_province' => 62, 'name' => 'Huyện Đông Hải'],
            ['id' => 696, 'id_province' => 62, 'name' => 'Huyện Hoà Bình'],
            ['id' => 697, 'id_province' => 63, 'name' => 'Thành phố Cà Mau'],
            ['id' => 698, 'id_province' => 63, 'name' => 'Huyện U Minh'],
            ['id' => 699, 'id_province' => 63, 'name' => 'Huyện Thới Bình'],
            ['id' => 700, 'id_province' => 63, 'name' => 'Huyện Trần Văn Thời'],
            ['id' => 701, 'id_province' => 63, 'name' => 'Huyện Cái Nước'],
            ['id' => 702, 'id_province' => 63, 'name' => 'Huyện Đầm Dơi'],
            ['id' => 703, 'id_province' => 63, 'name' => 'Huyện Năm Căn'],
            ['id' => 704, 'id_province' => 63, 'name' => 'Huyện Phú Tân'],
            ['id' => 705, 'id_province' => 63, 'name' => 'Huyện Ngọc Hiển'],
        ]);
    }
}
